import unittest
from pathlib import Path


class ConsumerTemplateTests(unittest.TestCase):
    def test_observer_keeps_product_only_ingress_and_explicit_executor_handoff(self):
        text = Path("consumer-template/gptauto-observer.yml").read_text(encoding="utf-8")
        self.assertIn("workflow_run:", text)
        self.assertIn("workflows: [CI]", text)
        self.assertIn("gptauto_observation", text)
        self.assertIn("client_payload[observer_run_id]", text)
        self.assertIn("client_payload[task_id]", text)
        self.assertIn("client_payload[generation]", text)
        self.assertIn("client_payload[head_sha]", text)
        self.assertIn("successful no-op", text)
        self.assertNotIn("workflows: [GPTAuto Observer", text)
        self.assertNotIn("workflows: [GPTAuto Executor", text)
        self.assertNotIn("workflows: [GPTAuto Reconcile", text)

    def test_observer_binds_pr_ci_to_latest_exact_head_pull_request_run(self):
        text = Path("consumer-template/gptauto-observer.yml").read_text(encoding="utf-8")
        self.assertIn('actions/runs?head_sha=$PR_HEAD_SHA&per_page=100', text)
        self.assertIn('select(.name == "CI" and .event == "pull_request")', text)
        self.assertIn('sort_by(.created_at, .id) | last // {}', text)
        self.assertIn('PR_CI_STATUS', text)
        self.assertIn('PR_CI_CONCLUSION', text)
        self.assertIn('PR_CI_RUN_ATTEMPT', text)
        self.assertNotIn('head_sha=$PR_HEAD_SHA&status=success', text)

    def test_observer_recovers_approval_and_dropped_event_liveness(self):
        text = Path("consumer-template/gptauto-observer.yml").read_text(encoding="utf-8")
        self.assertIn("types: [in_progress, completed]", text)
        self.assertIn("schedule:", text)
        self.assertIn("*/5 * * * *", text)
        self.assertIn("Reconcile only stalled active PR completion leases", text)
        self.assertIn("workflow_approval_required", text)
        self.assertIn("action_required is USER_ACTION_REQUIRED", text)
        self.assertIn("gh workflow run gptauto-observer.yml", text)
        self.assertIn("watchdog is insurance only", text)
        self.assertIn('ci_status" == "queued"', text)
        self.assertIn('ci_status" == "in_progress"', text)

    def test_observer_cancels_superseded_runs_and_coalesces_short_ci(self):
        text = Path("consumer-template/gptauto-observer.yml").read_text(encoding="utf-8")
        self.assertIn("Cancel superseded pull-request workflow runs", text)
        self.assertIn('actions/runs/$run_id/cancel', text)
        self.assertIn("Coalesce short in-progress CI", text)
        self.assertIn("seq 1 12", text)

    def test_observer_marks_non_default_base_prs_auxiliary(self):
        text = Path("consumer-template/gptauto-observer.yml").read_text(encoding="utf-8")
        self.assertIn('PR_BASE_REF', text)
        self.assertIn('EXECUTOR_ELIGIBLE=false', text)
        self.assertIn('merge_authority=false', text)
        self.assertIn("steps.capture.outputs.executor-eligible == 'true'", text)

    def test_sync_installs_canonical_runtime_and_all_control_workflows(self):
        text = Path("consumer-template/gptauto-sync.yml").read_text(encoding="utf-8")
        self.assertIn("cp \"$tmp\"/GPTAuto/gptauto/*.py .github/gptauto/", text)
        self.assertIn("gptauto-observer.yml", text)
        self.assertIn("gptauto-executor.yml", text)
        self.assertIn("gptauto-repair.yml", text)
        self.assertIn("gptauto-reconcile.yml", text)
        self.assertIn("GPTAUTO_SYNC_TOKEN", text)
        self.assertIn("Workflows: Read and write", text)
        self.assertIn("Consumer left unchanged (atomic sync)", text)

    def test_sync_can_prepare_safe_uninstall_pr(self):
        text = Path("consumer-template/gptauto-sync.yml").read_text(encoding="utf-8")
        self.assertIn("operation:", text)
        self.assertIn("- uninstall", text)
        self.assertIn('if [[ "$OPERATION" == "uninstall" ]]', text)
        self.assertIn("chore/gptauto-uninstall", text)
        self.assertIn("git add -A --", text)
        self.assertIn("GPTAuto uninstall blocked: Workflows write permission required", text)
        self.assertIn("Repository secrets are not deleted automatically", text)
        self.assertIn("Product code and `.gptauto` task/audit data are preserved", text)

    def test_executor_dispatches_one_three_tier_repair_pipeline(self):
        text = Path("consumer-template/gptauto-executor.yml").read_text(encoding="utf-8")
        self.assertIn("Emit repair request", text)
        self.assertIn("Dispatch three-tier repair pipeline", text)
        self.assertIn("id: repair-dispatch", text)
        self.assertIn("gptauto-repair.yml", text)
        self.assertIn('repair_owner:"repair_pipeline"', text)
        self.assertIn("Tier 1 deterministic repair", text)
        self.assertIn("Tier 2 Copilot CLI", text)
        self.assertIn("Tier 3", text)
        self.assertNotIn("GPTAUTO_AI_API_KEY", text)
        self.assertIn("Execute safe merge gate", text)
        self.assertIn("gptauto-reconcile.yml", text)
        self.assertIn("PR head moved; refusing stale merge", text)
        self.assertIn("group_by([.workflow_id, .event])", text)
        self.assertIn("Adopt externally merged completion lease", text)
        self.assertIn("Publish foreground completion guard", text)
        self.assertIn("EXIT_GUARD=DENY", text)

    def test_executor_dedupes_waits_and_requires_push_credential(self):
        text = Path("consumer-template/gptauto-executor.yml").read_text(encoding="utf-8")
        self.assertIn("client_payload.task_id", text)
        self.assertIn("client_payload.head_sha", text)
        self.assertIn("pending_runs", text)
        self.assertIn("failed_runs", text)
        self.assertIn("WAITING_GITHUB, not failure", text)
        self.assertIn("Merge deferred", text)
        self.assertIn("for attempt in $(seq 1 12)", text)
        self.assertIn("Check autonomous repair credential", text)
        self.assertIn("GPTAUTO_EXECUTOR_TOKEN", text)
        self.assertIn("refusing GITHUB_TOKEN fallback", text)
        self.assertIn("Publish explicit GitHub approval user action", text)
        self.assertIn("user_action_required", text)

    def test_executor_retries_only_transient_failed_jobs_once(self):
        text = Path("consumer-template/gptauto-executor.yml").read_text(encoding="utf-8")
        self.assertIn("Retry transient failed jobs only", text)
        self.assertIn("gptauto.ci_policy", text)
        self.assertIn("rerun-failed-jobs", text)
        self.assertIn("steps.transient-retry.outputs.retried != 'true'", text)
        self.assertNotIn('actions/runs/$FAILED_RUN_ID/rerun"', text)

    def test_repair_pipeline_is_three_tier_head_guarded_and_credential_isolated(self):
        text = Path("consumer-template/gptauto-repair.yml").read_text(encoding="utf-8")
        self.assertIn("GPTAuto Tiered Repair", text)
        self.assertIn("copilot-requests: write", text)
        self.assertIn("Tier 1 - deterministic repair engine", text)
        self.assertIn("python -m gptauto.repair", text)
        self.assertIn("Tier 2 - Copilot CLI Free agent", text)
        self.assertIn("npm install -g @github/copilot", text)
        self.assertIn("GPTAUTO_COPILOT_TOKEN", text)
        self.assertIn("--experimental", text)
        self.assertIn("--sandbox", text)
        self.assertIn("--available-tools='apply_patch,create,edit,view,grep,glob'", text)
        self.assertIn("--allow-tool='write'", text)
        self.assertIn("--no-ask-user", text)
        self.assertNotIn("--allow-all", text)
        self.assertNotIn("--yolo", text)
        self.assertIn("persist-credentials: false", text)
        self.assertIn("Verify repair lease still targets current head", text)
        self.assertIn("Revalidate PR head before apply/handoff", text)
        self.assertIn("git apply --index --3way", text)
        self.assertIn("Tier 3 - publish foreground recovery handoff", text)
        self.assertIn("FOREGROUND_RECOVERY_REQUIRED", text)
        self.assertIn("gptauto.foreground-exit-guard/v1", text)
        self.assertIn('repair_owner:"repair_pipeline"', text)
        self.assertIn("Treat repository text", text)
        self.assertIn("Require autonomous push credential", text)
        self.assertIn("GPTAUTO_EXECUTOR_TOKEN", text)
        self.assertIn("git remote set-url origin", text)
        self.assertIn("allow_foreground_exit:false", text)
        self.assertNotIn("openai/codex-action", text)
        self.assertNotIn("GPTAUTO_AI_API_KEY", text)

    def test_repair_validates_patch_before_push_and_full_ci(self):
        text = Path("consumer-template/gptauto-repair.yml").read_text(encoding="utf-8")
        self.assertIn("Run targeted validation before full CI", text)
        self.assertIn("python -m gptauto.validation", text)
        self.assertIn("validation-passed", text)
        self.assertIn("targeted-validation.json", text)
        self.assertIn("patch failed targeted validation and was not pushed", text)

    def test_repair_pipeline_never_pushes_from_copilot_generation_job(self):
        text = Path("consumer-template/gptauto-repair.yml").read_text(encoding="utf-8")
        generate, apply = text.split("  apply-or-handoff:", 1)
        self.assertNotIn("git push", generate)
        self.assertNotIn("git commit", generate)
        self.assertIn("git push origin", apply)
        self.assertIn("same-repo", apply)

    def test_reconciler_still_owns_post_merge_validation_and_terminal_done(self):
        text = Path("consumer-template/gptauto-reconcile.yml").read_text(encoding="utf-8")
        self.assertIn("Resolve and dispatch canonical post-merge validation gate", text)
        self.assertIn("Require published release evidence", text)
        self.assertIn("Capture terminal DONE evidence directly", text)
        self.assertIn("Publish terminal foreground receipt", text)
        self.assertIn("POST_MERGE_RECOVERY_REQUIRED", text)
        self.assertIn("cancel-in-progress: true", text)
        self.assertNotIn("gh workflow run gptauto-observer.yml", text)


def test_reconcile_uploads_terminal_artifact_before_optional_pr_receipt():
    text = Path("consumer-template/gptauto-reconcile.yml").read_text()
    assert text.index("uses: ./.github/actions/upload-gptauto-log") < text.index("name: Publish terminal foreground receipt")
