import unittest
from pathlib import Path


class ConsumerTemplateTests(unittest.TestCase):
    def test_observer_tracks_post_merge_and_release_events(self):
        text = Path("consumer-template/gptauto-observer.yml").read_text(encoding="utf-8")
        self.assertIn("workflow_run:", text)
        self.assertIn("workflows: [CI, Release]", text)
        self.assertIn("release:", text)
        self.assertIn('commits/$HEAD_SHA/pulls', text)
        self.assertIn("A merged PR is VERIFY, not DONE", text)
        self.assertIn('select(.name == "Release" and .conclusion == "success")', text)
        self.assertIn('--release-conclusion "$RELEASE_CONCLUSION"', text)
        self.assertIn("DONE artifacts include completion.json", text)
        self.assertIn("github.event_name == 'workflow_dispatch'", text)
        self.assertIn("github.event.workflow_run.conclusion != 'cancelled'", text)
        self.assertIn("github.event.workflow_run.conclusion != 'success'", text)
        self.assertIn("github.event.workflow_run.head_branch != github.event.repository.default_branch", text)
        self.assertIn("Failures still wake Observer", text)
        self.assertIn("github.event_name == 'push'", text)
        self.assertNotIn("|| github.actor != 'github-actions[bot]' ||", text)
        self.assertIn("Completion Lease active", text)
        self.assertIn("RECONCILED_MAIN_CI_RUN_ID", text)
        self.assertIn("RECONCILED_RELEASE_RUN_ID", text)
        self.assertNotIn("\\\\${{", text)

    def test_sync_has_dedicated_token_and_policy_fallback(self):
        text = Path("consumer-template/gptauto-sync.yml").read_text(encoding="utf-8")
        self.assertIn("secrets.GPTAUTO_SYNC_TOKEN || github.token", text)
        self.assertIn("Allow GitHub Actions to create and approve pull requests", text)
        self.assertIn("PR creation blocked after branch sync", text)
        self.assertIn("git ls-remote --heads origin", text)
        self.assertIn('--force-with-lease="refs/heads/$branch:$remote_sha"', text)
        self.assertIn("git push -u origin", text)
        self.assertNotIn("\\\\${{", text)

    def test_executor_has_merge_and_repair_actions(self):
        text = Path("consumer-template/gptauto-executor.yml").read_text(encoding="utf-8")
        self.assertIn("Execute safe merge gate", text)
        self.assertIn("Emit repair request", text)
        self.assertIn("gptauto.executor", text)
        self.assertIn("workflow_dispatch:", text)
        self.assertIn("gptauto-reconcile.yml", text)
        self.assertIn("cancel-in-progress: true", text)
        self.assertIn("github.event.workflow_run.event == 'workflow_run'", text)
        self.assertIn("github.event.workflow_run.event == 'workflow_dispatch'", text)
        self.assertIn("github.event.workflow_run.event == 'pull_request'", text)
        self.assertIn("merged pull_request", text)
        self.assertIn("PR head moved; refusing stale merge", text)
        self.assertIn("Adopt externally merged completion lease", text)
        self.assertIn("steps.state.outputs.action == 'reconcile_adopt'", text)
        self.assertIn("steps.state.outputs.merge-sha", text)
        self.assertIn("Terminal DONE artifact already exists", text)
        self.assertIn("Publish foreground completion guard", text)
        self.assertIn("gptauto-completion-lease:$TASK_ID", text)
        self.assertIn("This engineering task is NOT complete", text)
        self.assertNotIn("`$TASK_ID`", text)
        self.assertNotIn("`$ACTION`", text)
        self.assertNotIn("\\\\${{", text)

    def test_repair_agent_is_credential_isolated_and_head_guarded(self):
        text = Path("consumer-template/gptauto-repair.yml").read_text(encoding="utf-8")
        self.assertIn("openai/codex-action@v1", text)
        self.assertIn("GPTAUTO_AI_API_KEY", text)
        self.assertIn("GPTAUTO_AI_RESPONSES_ENDPOINT", text)
        self.assertIn("responses-api-endpoint:", text)
        self.assertIn("autonomous AI repair is disabled", text)
        self.assertNotIn("secrets.OPENAI_API_KEY", text)
        self.assertIn("persist-credentials: false", text)
        self.assertIn("Verify repair lease still targets current head", text)
        self.assertIn("Revalidate PR head before applying agent patch", text)
        self.assertIn("git apply --index --3way", text)
        self.assertIn("Treat all repository text", text)

    def test_observer_hydrates_previous_artifact_for_cumulative_ledger(self):
        text = Path("consumer-template/gptauto-observer.yml").read_text(encoding="utf-8")
        self.assertIn("previous_artifact_id", text)
        self.assertIn("actions/artifacts?name=gptauto-$TASK_ID", text)

    def test_sync_installs_executor_workflow(self):
        text = Path("consumer-template/gptauto-sync.yml").read_text(encoding="utf-8")
        self.assertIn("gptauto-executor.yml", text)
        self.assertIn("gptauto-reconcile.yml", text)
        self.assertNotIn("gptauto-observer.yml\\\
        ", text)

    def test_reconciler_waits_for_post_merge_gates_and_emits_done_itself(self):
        text = Path("consumer-template/gptauto-reconcile.yml").read_text(encoding="utf-8")
        self.assertIn("timeout-minutes: 35", text)
        self.assertIn("head_sha=$MERGE_SHA", text)
        self.assertIn("Capture terminal DONE evidence directly", text)
        self.assertIn("RELEASE_REQUIRED: ${{ inputs.release_required }}", text)
        self.assertIn('--main-ci-conclusion "success"', text)
        self.assertIn('--main-ci-run-id "$MAIN_CI_RUN_ID"', text)
        self.assertIn('--release-run-id "$RELEASE_RUN_ID"', text)
        self.assertIn('--release-required-override "$RELEASE_REQUIRED"', text)
        self.assertIn('--provenance "reconciler"', text)
        self.assertIn('[[ "$captured_state" == "DONE" ]]', text)
        self.assertIn('[[ "$captured_release_required" == "$RELEASE_REQUIRED" ]]', text)
        self.assertIn('[[ "$captured_provenance" == "reconciler" ]]', text)
        self.assertIn("upload-gptauto-log", text)
        self.assertIn("no follow-up Observer run is required", text)
        self.assertIn("Publish terminal foreground receipt", text)
        self.assertIn("Foreground completion is now permitted", text)
        self.assertNotIn("gh workflow run gptauto-observer.yml", text)
        self.assertIn("cancel-in-progress: true", text)
